- name: serup cart
  hosts: cart
  become: yes
  tasks:
  - name: diabling and enabling nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  
  - name: installing nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: Recursively remove directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name:  create directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: add roboshp
    ansible.builtin.user:
      name: roboshop

  - name: Download application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: npm install
    ansible.builtin.package:
      name: npm
      state: present

  - name: copy cart service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enable and start cart
    ansible.builtin.service:
      name: cart
      enabled: yes
      state: started