- name: catalogue configuartion
  hosts: catalogue
  become: yes
  tasks:
  - name: disable and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: installing nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  
  - name: creating roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Downloading application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: extract catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes


  - name: installing npm 
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: Copy catalogue
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  
  - name: deamon realod and start
    ansible.builtin.systemd_service:
      daemon_reload: true

    # let's start after the data is loaded

  - name: Copy mongo repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: installing mongodb-org-shell
    ansible.builtin.package: 
      name: mongodb-org-shell
      state: present

  
  - name: get the categories count
    ansible.builtin.command:  mongo --host mongodb.mvaws.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count

  # - name: print the count
  #   ansible.builtin.debug:
  #     msg: "product count: {{product_count}}"

  - name: load catalogue data
    ansible.builtin.command: mongo --host mongodb.mvaws.online < /app/schema/catalogue.js
    when: product_count.stdout == "0" # keep double quotes

  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes
  