- name: setup rabbitmq
  hosts: rabbitmq
  become: yes
  tasks:
  - name: config yum repos
    ansible.builtin.command: https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
  
  - name: repos for rabbitmq
    ansible.builtin.command: https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

  - name: install rabbitmq-server 
    ansible.builtin.package:
      name:  rabbitmq-server 
      state: present
  
  - name: enable and start rabbitmq-server 
    ansible.builtin.service:
      name: rabbitmq-server 
      state: started
      enabled: yes

  
  - name: create rabbitmq user
    ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

  - name: set permissions
    ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"