- name: redis configuration
  hosts: redis
  become: yes
  tasks:
  - name: install remi relase 
    ansible.builtin.dnf:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
      state: present
      disable_gpg_check: true
  
  - name: enabling redis
    ansible.builtin.service
      name: redis:remi-6.2
      enabled: yes

  - name: installing redis
    ansible.builtin.dnf:
      name: redis -y
      state: present

  - name: Replace old hostname with new hostname 
    ansible.builtin.replace:
      path: /etc/redis.conf
      regexp: 127.0.0.1
      replace: 0.0.0.0 

    - name: start and enable redis
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes